# tools/vector_store.py
# Semantic vector store for lending policy retrieval using ChromaDB + Ollama embeddings.
# Embeddings are generated by nomic-embed-text (or all-minilm fallback) via Ollama.
# Falls back gracefully to None if Ollama or ChromaDB is unavailable.

import json
import os
import requests
from typing import List, Optional

POLICY_STORE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "data", "processed", "lending_policy.json"
)
VECTORSTORE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "data", "processed", "policy_vectorstore"
)

OLLAMA_EMBED_URL = "http://localhost:11434/api/embed"
EMBED_MODEL_PRIMARY = "nomic-embed-text"
EMBED_MODEL_FALLBACK = "all-minilm"
EMBED_TIMEOUT = 30

COLLECTION_NAME = "lending_policy"

# ---------------------------------------------------------------------------
# Ollama embedding helper
# ---------------------------------------------------------------------------

def _get_embedding(text: str) -> Optional[List[float]]:
    """
    Get a text embedding from Ollama. Tries primary model, then fallback.
    Returns None if Ollama is unavailable.
    """
    for model in (EMBED_MODEL_PRIMARY, EMBED_MODEL_FALLBACK):
        try:
            resp = requests.post(
                OLLAMA_EMBED_URL,
                json={"model": model, "input": text},
                timeout=EMBED_TIMEOUT,
            )
            resp.raise_for_status()
            data = resp.json()
            embeddings = data.get("embeddings", [])
            if embeddings:
                return embeddings[0]
        except Exception:
            continue
    return None


# ---------------------------------------------------------------------------
# ChromaDB collection access
# ---------------------------------------------------------------------------

def _get_collection():
    """
    Return the ChromaDB persistent collection for lending policy clauses.
    Returns None if ChromaDB is unavailable.
    """
    try:
        import chromadb
        client = chromadb.PersistentClient(path=VECTORSTORE_PATH)
        return client.get_or_create_collection(
            name=COLLECTION_NAME,
            metadata={"hnsw:space": "cosine"},
        )
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Build / rebuild vector store
# ---------------------------------------------------------------------------

def build_vector_store() -> bool:
    """
    Load all policy clauses from lending_policy.json, embed them via Ollama,
    and persist to ChromaDB.

    Returns True on success, False if Ollama or ChromaDB is unavailable.
    """
    try:
        with open(POLICY_STORE_PATH, "r") as f:
            data = json.load(f)
        policies = data.get("policies", [])
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"[vector_store] Failed to load policy store: {e}")
        return False

    collection = _get_collection()
    if collection is None:
        print("[vector_store] ChromaDB unavailable — skipping vector store build.")
        return False

    ids, embeddings, documents, metadatas = [], [], [], []

    for policy in policies:
        clause_text = f"{policy['id']}: {policy['clause']}"
        embedding = _get_embedding(clause_text)
        if embedding is None:
            print(f"[vector_store] Ollama unavailable — cannot embed {policy['id']}.")
            return False

        ids.append(policy["id"])
        embeddings.append(embedding)
        documents.append(clause_text)
        metadatas.append({
            "id": policy["id"],
            "category": policy.get("category", ""),
            "trigger_tiers": ",".join(policy.get("trigger_tiers", [])),
            "trigger_conditions": ",".join(policy.get("trigger_conditions", [])),
        })

    # Upsert so rebuilding is idempotent
    collection.upsert(
        ids=ids,
        embeddings=embeddings,
        documents=documents,
        metadatas=metadatas,
    )

    print(f"[vector_store] Built vector store with {len(ids)} policy clauses.")
    return True


# ---------------------------------------------------------------------------
# Semantic retrieval
# ---------------------------------------------------------------------------

def retrieve_similar_clauses(query: str, n_results: int = 3) -> List[str]:
    """
    Return the n most semantically similar policy clause strings for a given query.
    Returns an empty list if the vector store or Ollama is unavailable.
    """
    collection = _get_collection()
    if collection is None:
        return []

    # Check collection has data
    try:
        if collection.count() == 0:
            return []
    except Exception:
        return []

    query_embedding = _get_embedding(query)
    if query_embedding is None:
        return []

    try:
        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=min(n_results, collection.count()),
            include=["documents"],
        )
        return results["documents"][0] if results["documents"] else []
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Availability check
# ---------------------------------------------------------------------------

def is_vector_store_available() -> bool:
    """
    Return True if the vector store has been built and contains data.
    Used by policy_retrieval.py to decide whether to use semantic or keyword search.
    """
    collection = _get_collection()
    if collection is None:
        return False
    try:
        return collection.count() > 0
    except Exception:
        return False
